version: 2
updates:
  # Monitor GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "develop"
    open-pull-requests-limit: 3

  # Monitor Go dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    target-branch: "develop"
    open-pull-requests-limit: 3

  