apiVersion: 1

datasources:
  - name: Prometheus (Local)
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 5s

  - name: Prometheus (Production)
    type: prometheus
    access: proxy
    url: http://gosearch1.dk:9090
    isDefault: false
    editable: true
    jsonData:
      timeInterval: 5s
      httpMethod: GET
    secureJsonData: {}
